apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-12T08:05:29Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4111"
  uid: e82fd7cf-f1a5-475d-b854-6b4591608f59
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.146.134
  clusterIPs:
  - 10.104.146.134
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32509
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
